version: '3.8'

services:
  tiktok-text-overlay-api:
    build: .
    container_name: tiktok-text-overlay-api
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - HOST=0.0.0.0
    volumes:
      - ./temp:/app/temp
      - ./fonts:/app/fonts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s